[build-system]
requires = ["setuptools>=61.2"]
build-backend = "setuptools.build_meta"

[project]
description = "An easy to use CUDA/OpenCL kernel tuner in Python"
name = "kernel_tuner"
python = ">=3.7"
version = "0.4.5"
authors = [
    { name = "Ben van Werkhoven", email = "b.vanwerkhoven@esciencecenter.nl" },
]
license = { file = "LICENSE" }
keywords = [
    "auto-tuning",
    "gpu",
    "computing",
    "pycuda",
    "cuda",
    "pyopencl",
    "opencl",
]
classifiers = [
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Education",
    "License :: OSI Approved :: Apache Software License",
    "Natural Language :: English",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development",
    "Topic :: System :: Distributed Computing",
    "Development Status :: 5 - Production/Stable",
]
dependencies = [
    "numpy>=1.13.3,<1.24.0",
    "scipy>=1.8.1",
    "jsonschema",
    "python-constraint",
    "xmltodict",
    "pandas",
]

[project.readme]
file = "README.rst"
content-type = "text/x-rst"

[project.urls]
Homepage = "https://KernelTuner.github.io/kernel_tuner/"
Documentation = "https://KernelTuner.github.io/kernel_tuner/"
Source = "https://github.com/KernelTuner/kernel_tuner"
Tracker = "https://github.com/KernelTuner/kernel_tuner/issues"

[project.optional-dependencies]
doc = [
    "sphinx",
    "sphinx_rtd_theme",
    "nbsphinx",
    "pytest",
    "ipython",
    "markupsafe==2.0.1",
]
cuda = ["pycuda", "nvidia-ml-py", "pynvml>=11.4.1"]
opencl = ["pyopencl"]
cuda_opencl = ["pycuda", "pyopencl"]
tutorial = ["jupyter", "matplotlib", "pandas"]
dev = [
    "numpy>=1.13.3",
    "scipy>=0.18.1",
    "mock>=2.0.0",
    "pytest>=3.0.3",
    "ruff >= 0.0.263",
    "Sphinx>=1.4.8",
    "scikit-learn>=0.24.2",
    "scikit-optimize>=0.8.1",
    "sphinx-rtd-theme>=0.1.9",
    "nbsphinx>=0.2.13",
    "jupyter>=1.0.0",
    "matplotlib>=1.5.3",
    "pandas>=0.19.1",
    "pylint>=1.7.1",
    "bayesian-optimization>=1.0.1",
]

[tool.setuptools]
packages = [
    "kernel_tuner",
    "kernel_tuner.backends",
    "kernel_tuner.energy",
    "kernel_tuner.observers",
    "kernel_tuner.runners",
    "kernel_tuner.strategies",
]
include-package-data = true

[tool.pytest.ini_options]
testpaths = ["test"]

[tool.black]
line-length = 120
[tool.ruff]
line-length = 120
respect-gitignore = true
exclude = ["doc"]
select = [
    "E", # pycodestyle
    "F", # pyflakes,
    "D", # pydocstyle,
]
# target-version = "py310"   # inferred from project.requires-python
[tool.ruff.pydocstyle]
convention = "google"
