# This workflow will use Nox to run tests and lint for the supported Python versions, and upload the test coverage data.

name: Build & Test

on:
    push:
        branches:
            - master
            - release/*
    pull_request:
        branches:
            - master

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build:
        name: Test on ${{ matrix.os }} with all supported Python versions
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]

        steps:
            - uses: actions/checkout@v4
            - uses: fjwillemsen/setup-nox2@v3.0.0
            - run: nox
            # TODO use with Codecov instead: https://github.com/marketplace/actions/codecov
            # - name: Report to Coveralls
            #   uses: coverallsapp/github-action@v2
            #   with:
            #       file: ".coverage"
